name: Convert LaTeX from Remote Repo to Markdown

on:
  workflow_dispatch:
    inputs:
      source_repo:
        description: 'Source repository (e.g., your-username/repo-a)'
        required: true
      source_branch:
        description: 'Branch in source repository to convert from'
        required: true
        default: 'original-filtered'
      output_branch:
        description: 'Branch in this repository to push converted files to'
        required: true
        default: 'markdown-conversion'

permissions:
  contents: write

env:
  OUTPUT_DIR: ./markdown_output
  SOURCE_CHECKOUT_DIR: ./source_repo_temp

jobs:
  convert_from_remote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository (Repo B)
        uses: actions/checkout@v4

      - name: Checkout source repository (Repo A)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.source_repo }}
          ref: ${{ github.event.inputs.source_branch }}
          path: ${{ env.SOURCE_CHECKOUT_DIR }}
          token: ${{ secrets.REPO_A_PAT }}

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Set up TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: scheme-medium

      - name: Convert TeX to Markdown
        run: |
          mkdir -p "${OUTPUT_DIR}"

          find "${SOURCE_CHECKOUT_DIR}" -type f -name '*.tex' -print0 | while IFS= read -r -d '' tex_file; do
            rel_path="${tex_file#${SOURCE_CHECKOUT_DIR}/}"
            [ "${rel_path}" = "$tex_file" ] && continue

            # Пропустити зайве
            [[ "$rel_path" == ".git/"* || "$rel_path" == *".sty" ]] && continue

            out_md="${OUTPUT_DIR}/${rel_path%.tex}.md"
            mkdir -p "$(dirname "$out_md")"

            echo "Converting $tex_file to $out_md"
            pandoc --from=latex+raw_tex \
                   --to=gfm \
                   --output="$out_md" \
                   --resource-path="${SOURCE_CHECKOUT_DIR}:$(dirname "$tex_file")" \
                   --citeproc \
                   --wrap=none \
                   "$tex_file" || echo "Warning: Pandoc failed for $tex_file"
          done

      - name: Commit and push to output branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -B "${{ github.event.inputs.output_branch }}"

          git rm -rf .
          git clean -fdx

          rm -rf "${SOURCE_CHECKOUT_DIR}/.git"
          rm -f .gitmodules

          if [ -d "${OUTPUT_DIR}" ] && [ "$(ls -A "${OUTPUT_DIR}")" ]; then
            cp -r ${OUTPUT_DIR}/* .
          else
            echo "No files to commit"
            touch .empty_conversion_result
          fi

          git add -A

          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Converted LaTeX to Markdown from ${{ github.event.inputs.source_repo }}/${{ github.event.inputs.source_branch }}"
            git push --force origin "${{ github.event.inputs.output_branch }}"
          fi
